### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by ema2159** [neutaaaaan/iosvkem#5]
No issue here, just passed by to say I think this is a beautiful theme. I use your implementation in doom themes (I'm also a maintainer) and I wanted to give you props for creating it, it's  really really nice.

**Comment by neutaaaaan** [comment]
Oh nice.

I wasn't really happy with the state it was in when I submitted to Henrik, but I figured it needed being slapped around by users so I could figure out what was missing.  
I guess I did too good of a job implementing the rough draft because I never got any feedback letting me know what was broken, or what looked weird. :smile: 

Life circumstances not being the absolute best at the time, and having lost most of my interest in the emacs platform, I drifted away from the project and let Henrik decide what he thought was best.  

Feel free to get in touch with me if you're ever unsure about some of your modifications, I never let an opportunity to bicker with people go to waste. :smile:
